### ISSUE TITLE
Home - Movie genre

### ISSUE THREAD

**Issue by idaenglund** [chas-academy/centaurs-06-imdb-clone#14]

**Comment by axelolsson** [comment]
25 days since this issue was opened. Progress?

**Comment by Andreas-sjolund-chas** [comment]
This is what I asked you about yesterday, we've been looking at this issue from time to time but gotten stuck here and there. Resulting in replanning and starting over with another approach.
It's on the way!

**Comment by axelolsson** [comment]
Alright, next time you get stuck - ask me straight away. No more issues that stay in progress for more than a couple of days. Please.
