### ISSUE TITLE
Password reset seems broken

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/centaurs-06-imdb-clone#186]
![screen shot 2018-03-02 at 11 20 27](https://user-images.githubusercontent.com/343422/36894483-c62d8c58-1e0b-11e8-88c1-efd5d7f83cd7.png)

**Comment by axelolsson** [comment]
You need to provide credentials for SwiftMailer to be able to send emails in production.

**Comment by axelolsson** [comment]
@Ciavarella I believe you tried and got this working locally.

**Comment by axeberg** [comment]
@Ciavarella fixed?
