### ISSUE TITLE
Search seems broken

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/centaurs-06-imdb-clone#187]
Doesn't matter what I search for but I keep getting an exception thrown:

![screen shot 2018-03-02 at 11 21 28](https://user-images.githubusercontent.com/343422/36894515-e272c306-1e0b-11e8-9268-a00979e24b2c.png)

**Comment by Andreas-sjolund-chas** [comment]
This issue is now resolved in the latest deploy
