### ISSUE TITLE
Missing some required documentation

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/centaurs-06-imdb-clone#193]
According to the hand-in you need to include personas and scenarios, as well as a sitemap. Please provide links to those below AND in the README for future reference.

**Comment by Ciavarella** [comment]
https://drive.google.com/drive/u/0/folders/1Sou3F6HYZOqwudGH_Gn23GjaBzata3t7

**Comment by axelolsson** [comment]
👍 Wonderful thanks!

One small thing though, in the requirements document you could refer to your wireframe.pdf in the section where the wireframes are supposed to be. :)
