### ISSUE TITLE
Images are broken in production

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/centaurs-06-imdb-clone#195]
Backdrop images and slideshows for seasons need to use either (w500, w780 or original in their paths).

https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400

**Comment by Andreas-sjolund-chas** [comment]
Pullrequest pending

**Comment by Andreas-sjolund-chas** [comment]
This is now fixed in the latest deploy
