### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by idaenglund** [chas-academy/centaurs-06-imdb-clone#20]

**Comment by Andreas-sjolund-chas** [comment]
This must be solved by the end of tuesday 12/12!

**Comment by Andreas-sjolund-chas** [comment]
Temporary url - http://165.227.236.122/

Master - Deploy_path = http://centaurs-imdb.me
Staging - Deploy_path = http://staging.centaurs-imdb.me
Develop - Deploy_path = http://develop.centaurs-imdb.me
