### ISSUE TITLE
Gitflow - branches

### ISSUE THREAD

**Issue by idaenglund** [chas-academy/centaurs-06-imdb-clone#22]

**Comment by Andreas-sjolund-chas** [comment]
We need to talk about our methods in merging and handling our branches so everyone is on the same page.

**Comment by Andreas-sjolund-chas** [comment]
Temporary url - http://165.227.236.122/

Master - Deploy_path = http://centaurs-imdb.me
Staging - Deploy_path = http://staging.centaurs-imdb.me
Develop - Deploy_path = http://develop.centaurs-imdb.me

**Comment by Andreas-sjolund-chas** [comment]
https://raygun.com/blog/git-workflow/
