### ISSUE TITLE
Style guideline

### ISSUE THREAD

**Issue by lalaya** [chas-academy/centaurs-06-imdb-clone#34]

**Comment by axelolsson** [comment]
@lalaya I'd like to see this if you have the time :)

**Comment by lalaya** [comment]
[Centaurs_identity.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a1bd9be1c699e001127f74a/125516c66e82c728ace21e0d46cb9194378396bb9cd6b647a153e49d3d5f653f6b14b1247a80e03cfd1839540e5d4bfd43505c4dfbf9892da0b63c71d85e0cef85385b66da2f53fde6d640e258f075c95d8fa4bd8c46c1ed3c26e58b894c3c19041e8ced10.pdf) It will probably need to be a more updated as we go.

**Comment by axelolsson** [comment]
@lalaya looks like a good way to get started but that logo looks so damn cool, good job!
