### ISSUE TITLE
Finish ERD @PontusSarland88

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/centaurs-06-imdb-clone#4]
Anywhere I can see the progress of this?

**Comment by PontusSarland88** [comment]
https://www.lucidchart.com/documents/view/08cba566-c0ad-4893-beee-6dcfdf89c777

**Comment by axelolsson** [comment]
@PontusSarland88 looking good, any particular reason why you're mixing snake_case and PascalCase in the chart?

**Comment by PontusSarland88** [comment]
@axelolsson nope, I will fix that :)

**Comment by axelolsson** [comment]
@PontusSarland88 perfect!
